// ============================================================
// DATA — 69 wilaya capital cities + 8 quiz questions
// Auto-generated from Gemini content + Wikidata P18 images
// ============================================================

const QUESTIONS = [
  {
    id: 1,
    question: "Beach or mountains?",
    options: [
      { label: "🌊 Beach", tags: { coastal: 3 } },
      { label: "🏔️ Mountains", tags: { mountain: 3 } },
    ],
  },
  {
    id: 2,
    question: "Fast-paced or chill?",
    options: [
      { label: "⚡ Fast-paced", tags: { fast: 3 } },
      { label: "🧘 Chill", tags: { chill: 3 } },
    ],
  },
  {
    id: 3,
    question: "Big city energy or small town warmth?",
    options: [
      { label: "🌆 Big city", tags: { urban: 3 } },
      { label: "🏘️ Small town", tags: { traditional: 3 } },
    ],
  },
  {
    id: 4,
    question: "Nightlife or early nights?",
    options: [
      { label: "🍸 Nightlife", tags: { nightlife: 3 } },
      { label: "🌙 Early nights", tags: { family: 3 } },
    ],
  },
  {
    id: 5,
    question: "Budget-conscious or don't care?",
    options: [
      { label: "💰 Budget-conscious", tags: { low_budget: 3 } },
      { label: "💎 Don't care", tags: { mid_budget: 3 } },
    ],
  },
  {
    id: 6,
    question: "Desert heat or four seasons?",
    options: [
      { label: "🏜️ Desert heat", tags: { desert: 3 } },
      { label: "🍂 Four seasons", tags: { temperate: 3 } },
    ],
  },
  {
    id: 7,
    question: "Historic vibes or modern life?",
    options: [
      { label: "🏛️ Historic city", tags: { historic: 3 } },
      { label: "🏗️ Modern city", tags: { modern: 3 } },
    ],
  },
  {
    id: 8,
    question: "Tourist hotspot or local secret?",
    options: [
      { label: "📸 Tourist favorite", tags: { touristy: 3 } },
      { label: "🤫 Hidden gem", tags: { local: 3 } },
    ],
  },
];

const CITIES = {
  adrar: {
    name: "Adrar",
    demonym: "ADRARIENNE",
    emoji: "🌴🔥",
    tagline: "Living that golden oasis dream life.",
    description: "You are the ultimate hidden gem, chilling in the middle of the dunes. You love keeping it real, traditional, and totally low-key.",
    vibe_tag: "Golden dunes and ancient desert whispers",
    image: "assets/wilayas/01-Adrar.jpg",
    tags: {
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 2,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  chlef: {
    name: "Chlef",
    demonym: "CHLEFIENNE",
    emoji: "🍊🚜",
    tagline: "Fresh vibes and farm-to-table energy.",
    description: "You are all about growth and keeping things grounded. You're a hardworking soul who values community and simple, honest living.",
    vibe_tag: "Where history meets the fertile valley",
    image: "assets/wilayas/02-Chlef.jpg",
    tags: {
    mountain: 1,
    temperate: 2,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    family: 3,
    low_budget: 2,
    mid_budget: 1,
    modern: 2,
    local: 3
    },
  },
  laghouat: {
    name: "Laghouat",
    demonym: "LAGHOUATIENNE",
    emoji: "🏜️✨",
    tagline: "The gateway to your next adventure.",
    description: "You are the bridge between the city and the wild Sahara. You've got a classic soul and you're always ready for a road trip.",
    vibe_tag: "Gateway to the vast Saharan horizon",
    image: "assets/wilayas/03-Laghouat.jpg",
    tags: {
    mountain: 1,
    desert: 2,
    temperate: 1,
    chill: 3,
    urban: 1,
    traditional: 3,
    family: 2,
    low_budget: 3,
    historic: 2,
    local: 3
    },
  },
  oum_el_bouaghi: {
    name: "Oum El Bouaghi",
    demonym: "OUM EL BOUAGHIENNE",
    emoji: "🌾☁️",
    tagline: "Quiet, steady, and perfectly low-key.",
    description: "You don't need the spotlight to shine. You value your peace and quiet, and you're the most reliable friend in the group.",
    vibe_tag: "High plateau spirit, rugged and raw",
    image: null,
    tags: {
    mountain: 1,
    temperate: 1,
    chill: 3,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  batna: {
    name: "Batna",
    demonym: "BATNÉENNE",
    emoji: "🎓🏔️",
    tagline: "Brainy, bold, and totally iconic.",
    description: "You are a total history buff with a revolutionary spirit. You love hanging out with friends and debating the big topics.",
    vibe_tag: "Mountain peaks and ancient Roman echoes",
    image: "assets/wilayas/05-Batna.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    fast: 2,
    chill: 1,
    urban: 2,
    traditional: 1,
    nightlife: 2,
    family: 1,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    modern: 1,
    local: 2,
    touristy: 1
    },
  },
  b_ja_a: {
    name: "Béjaïa",
    demonym: "BÉJAÏENNE",
    emoji: "🌊⛰️",
    tagline: "Coastal aesthetic and mountain views.",
    description: "You are the total package—beach days in the morning and mountain hikes in the afternoon. You're trendy, social, and always on the move.",
    vibe_tag: "Emerald coastlines and Mediterranean dreams",
    image: "assets/wilayas/06-B_ja_a.jpg",
    tags: {
    coastal: 3,
    mountain: 2,
    temperate: 2,
    fast: 3,
    urban: 2,
    traditional: 1,
    nightlife: 3,
    low_budget: 1,
    mid_budget: 2,
    historic: 1,
    modern: 2,
    local: 1,
    touristy: 3
    },
  },
  biskra: {
    name: "Biskra",
    demonym: "BISKRIENNE",
    emoji: "🌴☀️",
    tagline: "Sweetest vibes in the desert sun.",
    description: "You are vibrant, warm, and have a heart of gold—just like the famous dates you're known for. You're the life of the oasis.",
    vibe_tag: "Date palms and desert oasis magic",
    image: "assets/wilayas/07-Biskra.jpg",
    tags: {
    desert: 3,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    nightlife: 1,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 2,
    local: 2,
    touristy: 1
    },
  },
  b_char: {
    name: "Béchar",
    demonym: "BÉCHARIENNE",
    emoji: "🌵✊",
    tagline: "Rugged, raw, and ready for anything.",
    description: "You're a bit of a mystery. You love your independence and have a tough-as-nails personality that survives any challenge.",
    vibe_tag: "Sahara soul, timeless nomadic vibes",
    image: "assets/wilayas/08-B_char.jpg",
    tags: {
    mountain: 1,
    desert: 3,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    family: 2,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  blida: {
    name: "Blida",
    demonym: "BLIDAISE",
    emoji: "🌹✨",
    tagline: "City of roses and main character energy.",
    description: "You are super stylish and always surrounded by beauty. You're the one who organizes the weekend hangouts and keeps the squad together.",
    vibe_tag: "City of roses and mountain breezes",
    image: "assets/wilayas/09-Blida.jpg",
    tags: {
    coastal: 1,
    mountain: 1,
    temperate: 3,
    fast: 3,
    urban: 3,
    nightlife: 2,
    family: 2,
    low_budget: 1,
    mid_budget: 2,
    historic: 1,
    modern: 3,
    local: 1,
    touristy: 2
    },
  },
  bouira: {
    name: "Bouira",
    demonym: "BOUIRIENNE",
    emoji: "🌲🏔️",
    tagline: "Mountain soul with a quiet heart.",
    description: "You are deep, thoughtful, and love your roots. You prefer a slow pace and meaningful connections over the busy city rush.",
    vibe_tag: "Green hills and serene highland air",
    image: "assets/wilayas/10-Bouira.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    chill: 3,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  tamanrasset: {
    name: "Tamanrasset",
    demonym: "TAMANRASSETIENNE",
    emoji: "🌌✨",
    tagline: "Spiritual, stunning, and totally legendary.",
    description: "You are a traveler at heart. With your love for art, deep traditions, and epic landscapes, you're basically the coolest person anyone knows.",
    vibe_tag: "Heart of the desert, majestic peaks",
    image: "assets/wilayas/11-Tamanrasset.jpg",
    tags: {
    mountain: 2,
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 1,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    local: 2,
    touristy: 2
    },
  },
  t_bessa: {
    name: "Tébessa",
    demonym: "TÉBESSIENNE",
    emoji: "🏛️⏳",
    tagline: "Ancient history meets modern edge.",
    description: "You're a total time traveler who loves mixing the old-school with the new. You're sharp, strategic, and always have a story to tell.",
    vibe_tag: "Ancient stones and frontier desert tales",
    image: "assets/wilayas/12-T_bessa.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    nightlife: 1,
    family: 1,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    modern: 1,
    local: 2,
    touristy: 1
    },
  },
  tlemcen: {
    name: "Tlemcen",
    demonym: "TLEMCÉNIENNE",
    emoji: "🎨✨",
    tagline: "The artsy soul with timeless aesthetic vibes.",
    description: "You are the definition of 'old money' aesthetic meets creative genius. You love slow mornings, historical architecture, and finding beauty in the little details of life.",
    vibe_tag: "Andalusian grace in every corner",
    image: "assets/wilayas/13-Tlemcen.jpg",
    tags: {
    coastal: 1,
    mountain: 3,
    temperate: 2,
    chill: 3,
    urban: 1,
    traditional: 2,
    nightlife: 1,
    family: 2,
    low_budget: 1,
    mid_budget: 2,
    historic: 3,
    local: 2,
    touristy: 1
    },
  },
  tiaret: {
    name: "Tiaret",
    demonym: "TIARETIENNE",
    emoji: "🐎🌾",
    tagline: "Main character energy for horse lovers only.",
    description: "You’re low-key, grounded, and have a deep appreciation for heritage. You prefer wide open spaces and the company of your best friends over the noise of the big city.",
    vibe_tag: "Highland plains and wild equestrian spirit",
    image: "assets/wilayas/14-Tiaret.jpg",
    tags: {
    mountain: 2,
    temperate: 1,
    chill: 3,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 2,
    modern: 1,
    local: 3
    },
  },
  tizi_ouzou: {
    name: "Tizi Ouzou",
    demonym: "TIZI OUZIENNE",
    emoji: "🏔️✊",
    tagline: "Big mountain energy and fierce cultural pride.",
    description: "You are the loyal friend who always stands up for what they believe in. Your vibe is all about community, steep hills, and having the best stories to tell.",
    vibe_tag: "Mountain majesty and cultural pride",
    image: "assets/wilayas/15-Tizi_Ouzou.jpg",
    tags: {
    mountain: 3,
    temperate: 2,
    fast: 1,
    chill: 2,
    urban: 2,
    traditional: 2,
    nightlife: 1,
    family: 3,
    low_budget: 2,
    mid_budget: 1,
    historic: 1,
    modern: 2,
    local: 3
    },
  },
  algiers: {
    name: "Algiers",
    demonym: "ALGÉROISE",
    emoji: "🏙️🌊",
    tagline: "The chaotic, iconic center of everything cool.",
    description: "You are the life of the party and thrive in the fast lane. You’re always on the move, chasing the latest trends and soaking up the busy city lights.",
    vibe_tag: "The White City, sparkling by the sea",
    image: "assets/wilayas/16-Algiers.jpg",
    tags: {
    coastal: 3,
    temperate: 2,
    fast: 3,
    urban: 3,
    traditional: 1,
    nightlife: 3,
    mid_budget: 3,
    historic: 1,
    modern: 3,
    local: 1,
    touristy: 3
    },
  },
  djelfa: {
    name: "Djelfa",
    demonym: "DJELFIENNE",
    emoji: "🏜️🐑",
    tagline: "Steppe vibes and authentic desert-edge mystery.",
    description: "You’re a rugged individual who thrives in the quiet, vast landscapes. You value tradition and keeping it real over chasing the latest internet fads.",
    vibe_tag: "Steppe landscapes and nomadic heritage",
    image: "assets/wilayas/17-Djelfa.jpg",
    tags: {
    mountain: 1,
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 2,
    local: 3
    },
  },
  jijel: {
    name: "Jijel",
    demonym: "JIJELIENNE",
    emoji: "🏖️🌲",
    tagline: "Coastal aesthetic and pure vacation mode.",
    description: "You are the ultimate 'beach bum' who just wants to chill and enjoy the view. You keep things simple, breezy, and effortlessly cool.",
    vibe_tag: "Coastal cliffs and wild blue waters",
    image: "assets/wilayas/18-Jijel.jpg",
    tags: {
    coastal: 3,
    mountain: 2,
    temperate: 2,
    chill: 3,
    urban: 1,
    traditional: 1,
    nightlife: 1,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  s_tif: {
    name: "Sétif",
    demonym: "SÉTIFIENNE",
    emoji: "🎓📈",
    tagline: "Total hustle culture in a student city.",
    description: "You’re ambitious, social, and always looking for the next big opportunity. Whether you're studying or shopping, you’re always busy leveling up.",
    vibe_tag: "High altitude charm, vibrant city life",
    image: "assets/wilayas/19-S_tif.jpg",
    tags: {
    mountain: 1,
    temperate: 1,
    fast: 3,
    urban: 3,
    traditional: 1,
    nightlife: 2,
    family: 1,
    low_budget: 1,
    mid_budget: 2,
    historic: 2,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  sa_da: {
    name: "Saïda",
    demonym: "SAÏDIENNE",
    emoji: "⛰️☁️",
    tagline: "Low-key mountain retreat for true peace.",
    description: "You’re the friend everyone goes to when they need to escape the drama. You value quality time, fresh air, and a quiet, traditional way of life.",
    vibe_tag: "Thermal springs and lush green valleys",
    image: "assets/wilayas/20-Sa_da.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    chill: 3,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 1,
    modern: 1,
    local: 3
    },
  },
  skikda: {
    name: "Skikda",
    demonym: "SKIKDAISE",
    emoji: "⚓🌊",
    tagline: "Industrial grit meets beautiful turquoise shores.",
    description: "You’ve got a tough exterior but a soft spot for beauty. You’re hardworking and practical, but never say no to a sunset at the beach.",
    vibe_tag: "Azure waves and seaside serenity",
    image: "assets/wilayas/21-Skikda.jpg",
    tags: {
    coastal: 3,
    mountain: 1,
    temperate: 2,
    fast: 2,
    chill: 1,
    urban: 2,
    traditional: 1,
    nightlife: 1,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 2,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  sidi_bel_abb_s: {
    name: "Sidi Bel Abbès",
    demonym: "SIDI BEL ABBÉSIENNE",
    emoji: "🏛️🎓",
    tagline: "Historic plains city with major brain power.",
    description: "You’re a mix of old-school history and modern student life. You’re smart, steady, and have a unique perspective on where you come from.",
    vibe_tag: "Modern energy meets classic desert charm",
    image: "assets/wilayas/22-Sidi_Bel_Abb_s.jpg",
    tags: {
    mountain: 1,
    temperate: 1,
    fast: 1,
    chill: 2,
    urban: 2,
    traditional: 2,
    nightlife: 1,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    modern: 1,
    local: 3
    },
  },
  annaba: {
    name: "Annaba",
    demonym: "ANNABAISE",
    emoji: "🌊🏛️",
    tagline: "Classic Mediterranean vibes with a historic edge.",
    description: "You’re charming, historic, and effortlessly cool. You love a balance of beach days, late-night cafes, and hanging out with your favorite people.",
    vibe_tag: "The pearl of the Mediterranean coast",
    image: "assets/wilayas/23-Annaba.jpg",
    tags: {
    coastal: 3,
    mountain: 1,
    temperate: 2,
    fast: 2,
    chill: 1,
    urban: 2,
    traditional: 1,
    nightlife: 2,
    family: 1,
    low_budget: 1,
    mid_budget: 2,
    historic: 3,
    modern: 1,
    local: 1,
    touristy: 2
    },
  },
  guelma: {
    name: "Guelma",
    demonym: "GUELMIENNE",
    emoji: "♨️🌿",
    tagline: "Thermal spa vibes for the ultimate relaxer.",
    description: "You are all about self-care and finding your zen. You’re low-key obsessed with wellness and love exploring nature at your own pace.",
    vibe_tag: "Rolling hills and ancient thermal baths",
    image: "assets/wilayas/24-Guelma.jpg",
    tags: {
    mountain: 3,
    temperate: 2,
    chill: 3,
    traditional: 2,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 2,
    modern: 1,
    local: 3,
    touristy: 1
    },
  },
  constantine: {
    name: "Constantine",
    demonym: "CONSTANTINOISE",
    emoji: "🌉🎓",
    tagline: "Living life on the edge, literally.",
    description: "You are the intellectual powerhouse with a flair for the dramatic. You love deep convos, iconic views, and being the center of the cultural scene.",
    vibe_tag: "Suspended bridges over history's canyon",
    image: "assets/wilayas/25-Constantine.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    fast: 2,
    chill: 1,
    urban: 3,
    traditional: 1,
    nightlife: 2,
    family: 1,
    low_budget: 1,
    mid_budget: 2,
    historic: 2,
    modern: 2,
    local: 1,
    touristy: 2
    },
  },
  m_d_a: {
    name: "Médéa",
    demonym: "MÉDÉENNE",
    emoji: "🍎⛰️",
    tagline: "Lowkey vibes and mountain air.",
    description: "You're the friend who prefers a cozy weekend over a wild party. You appreciate the simple things like good food and peaceful mountain views.",
    vibe_tag: "Mountain vineyards and historical charm",
    image: "assets/wilayas/26-M_d_a.jpg",
    tags: {
    mountain: 3,
    temperate: 2,
    chill: 3,
    urban: 1,
    traditional: 2,
    family: 3,
    low_budget: 2,
    mid_budget: 1,
    historic: 1,
    modern: 1,
    local: 3
    },
  },
  mostaganem: {
    name: "Mostaganem",
    demonym: "MOSTAGANÉMOISE",
    emoji: "🌊⛵",
    tagline: "Sun, sand, and coastal chill.",
    description: "You are all about that effortless Mediterranean lifestyle. You love the ocean breeze and keeping things relaxed while enjoying your daily routine.",
    vibe_tag: "Sun-drenched shores and golden sands",
    image: "assets/wilayas/27-Mostaganem.jpg",
    tags: {
    coastal: 3,
    temperate: 2,
    fast: 1,
    chill: 3,
    urban: 2,
    traditional: 1,
    nightlife: 1,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 1,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  m_sila: {
    name: "M'Sila",
    demonym: "MSILIENNE",
    emoji: "🌾🌤️",
    tagline: "The quiet achiever of the plains.",
    description: "You’re steady, reliable, and always evolving. You don't need the spotlight to get things done, and you're perfectly happy in your own space.",
    vibe_tag: "Heart of the plains, golden energy",
    image: "assets/wilayas/28-M_Sila.jpg",
    tags: {
    desert: 1,
    temperate: 1,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    family: 3,
    low_budget: 3,
    historic: 1,
    modern: 1,
    local: 3
    },
  },
  mascara: {
    name: "Mascara",
    demonym: "MASCARAISE",
    emoji: "🍇📜",
    tagline: "Rooted in history, rich in soul.",
    description: "You have a deep respect for your roots and a strong personality. You’re proud, historic, and carry a certain timeless wisdom with you.",
    vibe_tag: "Vineyards and ancient warrior spirit",
    image: "assets/wilayas/29-Mascara.jpg",
    tags: {
    mountain: 2,
    temperate: 1,
    chill: 2,
    urban: 1,
    traditional: 3,
    family: 3,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    local: 3
    },
  },
  ouargla: {
    name: "Ouargla",
    demonym: "OUARGLIENNE",
    emoji: "🌵🔥",
    tagline: "Sahara heat with city beats.",
    description: "You’re ambitious and thrive in high-energy environments. You love blending ancient traditions with a modern, fast-paced professional life.",
    vibe_tag: "Gateway to the golden desert sands",
    image: "assets/wilayas/30-Ouargla.jpg",
    tags: {
    desert: 3,
    fast: 3,
    urban: 2,
    traditional: 2,
    nightlife: 1,
    family: 2,
    low_budget: 1,
    mid_budget: 2,
    historic: 2,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  oran: {
    name: "Oran",
    demonym: "ORANAISE",
    emoji: "💃🎶",
    tagline: "The life of the party, always.",
    description: "You are the definition of cosmopolitan. With your love for music, nightlife, and social scenes, you’re the friend everyone invites to the main event.",
    vibe_tag: "Radiating coastal energy and sunny vibes",
    image: "assets/wilayas/31-Oran.jpg",
    tags: {
    coastal: 3,
    temperate: 2,
    fast: 3,
    urban: 3,
    nightlife: 3,
    low_budget: 1,
    mid_budget: 2,
    historic: 1,
    modern: 3,
    local: 1,
    touristy: 3
    },
  },
  el_bayadh: {
    name: "El Bayadh",
    demonym: "EL BAYADIENNE",
    emoji: "🐏🏜️",
    tagline: "Gateway to the vast desert horizon.",
    description: "You’re a bit of a mystery who values tradition and the open road. You’re grounded and keep things real, always looking toward the next adventure.",
    vibe_tag: "High plateau winds and open skies",
    image: "assets/wilayas/32-El_Bayadh.jpg",
    tags: {
    mountain: 1,
    desert: 2,
    chill: 2,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  illizi: {
    name: "Illizi",
    demonym: "ILLIZIENNE",
    emoji: "🎨✨",
    tagline: "Ancient art, endless desert magic.",
    description: "You are a total explorer with a soul for discovery. You prefer breathtaking landscapes and quiet, profound connections over city noise.",
    vibe_tag: "Gateway to the Tassili wonders",
    image: "assets/wilayas/33-Illizi.jpg",
    tags: {
    mountain: 1,
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 1,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    local: 2,
    touristy: 2
    },
  },
  bordj_bou_arr_ridj: {
    name: "Bordj Bou Arréridj",
    demonym: "BORDJIENNE",
    emoji: "📱🏗️",
    tagline: "Innovating the future, one step ahead.",
    description: "You’re tech-savvy, fast-moving, and always working on a new project. You’re the friend who’s always got the latest gadget and big plans.",
    vibe_tag: "Crafting excellence in the highlands",
    image: "assets/wilayas/34-Bordj_Bou_Arr_ridj.jpg",
    tags: {
    mountain: 1,
    temperate: 1,
    fast: 3,
    urban: 2,
    traditional: 1,
    nightlife: 1,
    family: 2,
    low_budget: 1,
    mid_budget: 2,
    modern: 3,
    local: 2
    },
  },
  boumerd_s: {
    name: "Boumerdès",
    demonym: "BOUMERDÉSIENNE",
    emoji: "🎓🌊",
    tagline: "Student life by the seaside.",
    description: "You’re the perfect balance of student energy and coastal chill. You love being close to the action while keeping your life balanced and fun.",
    vibe_tag: "Where the sea kisses the forest",
    image: "assets/wilayas/35-Boumerd_s.jpg",
    tags: {
    coastal: 3,
    temperate: 2,
    fast: 2,
    chill: 1,
    urban: 2,
    traditional: 1,
    nightlife: 1,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  el_tarf: {
    name: "El Tarf",
    demonym: "EL TARFIENNE",
    emoji: "🌲🦌",
    tagline: "Nature’s hidden gem, stay wild.",
    description: "You’re the ultimate nature lover who finds peace in forests and lakes. You’re quiet, observant, and prefer a hike over a city street.",
    vibe_tag: "Wild nature and hidden coastal gems",
    image: "assets/wilayas/36-El_Tarf.jpg",
    tags: {
    coastal: 2,
    temperate: 3,
    chill: 3,
    traditional: 2,
    family: 2,
    low_budget: 3,
    local: 3,
    touristy: 1
    },
  },
  tindouf: {
    name: "Tindouf",
    demonym: "TINDOUFIENNE",
    emoji: "🌵☀️",
    tagline: "Tindouf: The ultimate rugged desert explorer.",
    description: "You are the definition of resilient and mysterious. You thrive in the deep silence of the Sahara where the stars are your only company.",
    vibe_tag: "Desert solitude under endless stars",
    image: "assets/wilayas/37-Tindouf.jpg",
    tags: {
    desert: 3,
    chill: 3,
    traditional: 2,
    family: 1,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  tissemsilt: {
    name: "Tissemsilt",
    demonym: "TISSEMSILTIENNE",
    emoji: "🏔️🧥",
    tagline: "Tissemsilt: Your cozy mountain escape.",
    description: "You’re all about those quiet, slow-paced vibes. You love a good sweater, a hot drink, and keeping things super low-key.",
    vibe_tag: "Quiet plains and rugged mountain paths",
    image: "assets/wilayas/38-Tissemsilt.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    chill: 3,
    traditional: 3,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 1,
    local: 3
    },
  },
  el_oued: {
    name: "El Oued",
    demonym: "EL OUEDIENNE",
    emoji: "🕌🌴",
    tagline: "El Oued: The aesthetic dome-dwelling dreamer.",
    description: "You have an eye for unique architecture and love the desert heat. You're deeply connected to your roots and the sweet taste of home.",
    vibe_tag: "City of a thousand domes, sandy",
    image: "assets/wilayas/39-El_Oued.jpg",
    tags: {
    desert: 3,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 3,
    family: 3,
    low_budget: 2,
    mid_budget: 1,
    historic: 2,
    local: 3,
    touristy: 1
    },
  },
  khenchela: {
    name: "Khenchela",
    demonym: "KHENCHELIENNE",
    emoji: "❄️🏔️",
    tagline: "Khenchela: Fierce, cold, and totally authentic.",
    description: "You’re proud of your heritage and you don’t let the cold weather stop you. You’re tough, loyal, and love being surrounded by nature.",
    vibe_tag: "Rugged cliffs and ancient Berber roots",
    image: "assets/wilayas/40-Khenchela.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    chill: 2,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  souk_ahras: {
    name: "Souk Ahras",
    demonym: "SOUK AHRASSIENNE",
    emoji: "🏛️🌲",
    tagline: "Souk Ahras: A historic soul in the mountains.",
    description: "You’re an old soul who loves stories from the past. Living near the border, you’re always curious about the world beyond.",
    vibe_tag: "Olive groves and historical crossroads",
    image: "assets/wilayas/41-Souk_Ahras.jpg",
    tags: {
    mountain: 3,
    temperate: 2,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    nightlife: 1,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    local: 2,
    touristy: 1
    },
  },
  tipaza: {
    name: "Tipaza",
    demonym: "TIPAZIENNE",
    emoji: "🌊🏛️",
    tagline: "Tipaza: Sun, sea, and ancient vibes.",
    description: "You live for the golden hour and beach days. You’re a total tourist magnet because your aesthetic is literally legendary.",
    vibe_tag: "Roman ruins by the turquoise sea",
    image: "assets/wilayas/42-Tipaza.jpg",
    tags: {
    coastal: 3,
    mountain: 1,
    temperate: 2,
    fast: 2,
    chill: 1,
    urban: 1,
    traditional: 1,
    nightlife: 2,
    family: 1,
    mid_budget: 3,
    historic: 3,
    modern: 1,
    touristy: 3
    },
  },
  mila: {
    name: "Mila",
    demonym: "MILIENNE",
    emoji: "🏺✨",
    tagline: "Mila: Quiet, classy, and timeless.",
    description: "You’re low-maintenance but deeply fascinating. You’re the friend everyone goes to when they need a calm, thoughtful conversation.",
    vibe_tag: "Ancient walls and deep valley secrets",
    image: "assets/wilayas/43-Mila.jpg",
    tags: {
    mountain: 3,
    temperate: 1,
    chill: 3,
    traditional: 2,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 3,
    local: 3
    },
  },
  a_n_defla: {
    name: "Aïn Defla",
    demonym: "AÏN DEFLIENNE",
    emoji: "🌾🚜",
    tagline: "Aïn Defla: The grounded, chill agricultural pro.",
    description: "You’re balanced and down-to-earth. You enjoy the simple life and know exactly how to make things grow and thrive.",
    vibe_tag: "Orchards, mountains, and peaceful charm",
    image: "assets/wilayas/44-A_n_Defla.jpg",
    tags: {
    mountain: 1,
    temperate: 3,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    modern: 1,
    local: 3
    },
  },
  na_ma: {
    name: "Naâma",
    demonym: "NAÂMIENNE",
    emoji: "🌅🐑",
    tagline: "Naâma: Steppe vibes and wild horizons.",
    description: "You’re a free spirit who loves open spaces. You’re a bit of an outsider, but that’s exactly what makes you so cool.",
    vibe_tag: "Desert dunes and sunset horizons",
    image: "assets/wilayas/45-Na_ma.jpg",
    tags: {
    mountain: 1,
    desert: 2,
    temperate: 1,
    chill: 3,
    traditional: 2,
    family: 2,
    low_budget: 3,
    local: 3
    },
  },
  a_n_t_mouchent: {
    name: "Aïn Témouchent",
    demonym: "AÏN TÉMOUCHENTIENNE",
    emoji: "🍇🏖️",
    tagline: "Aïn Témouchent: Coastal chic and vineyard dreams.",
    description: "You’re sophisticated, relaxed, and definitely the one with the best taste. You know how to enjoy the finer things without overdoing it.",
    vibe_tag: "Coastal beauty and sun-kissed shores",
    image: "assets/wilayas/46-A_n_T_mouchent.jpg",
    tags: {
    coastal: 3,
    temperate: 2,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 1,
    nightlife: 1,
    family: 2,
    low_budget: 1,
    mid_budget: 2,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  gharda_a: {
    name: "Ghardaïa",
    demonym: "GHARDAÏENNE",
    emoji: "🧿🏜️",
    tagline: "Ghardaïa: Iconic, spiritual, and totally unique.",
    description: "You’re one of a kind and everyone knows it. You take pride in your traditions and have a style that nobody can replicate.",
    vibe_tag: "Geometric wonders in the desert sun",
    image: "assets/wilayas/47-Gharda_a.jpg",
    tags: {
    desert: 3,
    chill: 3,
    urban: 1,
    traditional: 3,
    family: 2,
    low_budget: 1,
    mid_budget: 2,
    historic: 3,
    local: 2,
    touristy: 2
    },
  },
  relizane: {
    name: "Relizane",
    demonym: "RELIZANIENNE",
    emoji: "🌱⚡",
    tagline: "Relizane: Growing fast and staying real.",
    description: "You’re ambitious and always on the move. You’re building your future while staying connected to your roots in the plains.",
    vibe_tag: "Fertile lands and agricultural heart",
    image: "assets/wilayas/48-Relizane.jpg",
    tags: {
    temperate: 3,
    fast: 3,
    urban: 2,
    traditional: 1,
    nightlife: 2,
    family: 1,
    low_budget: 2,
    mid_budget: 1,
    modern: 2,
    local: 3
    },
  },
  timimoun: {
    name: "Timimoun",
    demonym: "TIMIMOUNIENNE",
    emoji: "🏜️✨",
    tagline: "The red oasis where aesthetic dreams live.",
    description: "You are the main character of a desert indie film. With your stunning red mud-brick aesthetic and chill vibes, you turn every sunset into a core memory.",
    vibe_tag: "Red oasis dreams in golden sands",
    image: "assets/wilayas/49-Timimoun.jpg",
    tags: {
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 2,
    low_budget: 3,
    historic: 3,
    local: 1,
    touristy: 2
    },
  },
  bordj_badji_mokhtar: {
    name: "Bordj Badji Mokhtar",
    demonym: "BORDJ BADJI MOKHTARIENNE",
    emoji: "📍🔥",
    tagline: "The ultimate frontier vibe for true explorers.",
    description: "You are mysterious, resilient, and totally off the grid. You thrive where the map ends and the real adventure begins.",
    vibe_tag: "Deep desert silence and starlit skies",
    image: "assets/wilayas/50-Bordj_Badji_Mokhtar.jpg",
    tags: {
    desert: 3,
    fast: 1,
    chill: 2,
    traditional: 3,
    family: 2,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  ouled_djellal: {
    name: "Ouled Djellal",
    demonym: "OULED DJELLALIENNE",
    emoji: "🌴☀️",
    tagline: "Keepin' it real in the golden palms.",
    description: "You are grounded, hardworking, and deeply connected to your roots. Life is simple, sweet, and centered around family gatherings.",
    vibe_tag: "Rising oasis in the vast desert",
    image: "assets/wilayas/51-Ouled_Djellal.jpg",
    tags: {
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 2,
    local: 3
    },
  },
  b_ni_abb_s: {
    name: "Béni Abbès",
    demonym: "BÉNI ABBÉSIENNE",
    emoji: "🏰🤍",
    tagline: "A white oasis straight out of Pinterest.",
    description: "You are the aesthetic friend who knows all the best photo spots. You keep things classy and serene, perfect for a peaceful getaway.",
    vibe_tag: "Gateway to the infinite Sahara sands",
    image: "assets/wilayas/52-B_ni_Abb_s.jpg",
    tags: {
    desert: 3,
    chill: 3,
    traditional: 2,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 2,
    modern: 1,
    local: 1,
    touristy: 2
    },
  },
  in_salah: {
    name: "In Salah",
    demonym: "IN SALAHIENNE",
    emoji: "⛽🌵",
    tagline: "Built different in the heart of heat.",
    description: "You are a powerhouse of energy and industry. Tough, resilient, and always focused on the bigger picture, you don't let the heat slow you down.",
    vibe_tag: "Where the desert meets the sky",
    image: "assets/wilayas/53-In_Salah.jpg",
    tags: {
    desert: 3,
    fast: 2,
    chill: 1,
    urban: 1,
    traditional: 2,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 1,
    modern: 2,
    local: 3
    },
  },
  in_guezzam: {
    name: "In Guezzam",
    demonym: "IN GUEZZAMIENNE",
    emoji: "🌍🐫",
    tagline: "The desert nomad with a global soul.",
    description: "You are the ultimate bridge between worlds. Cultural, open-minded, and always on the move, you represent the true spirit of the Sahara.",
    vibe_tag: "Borderland spirit in the deep south",
    image: "assets/wilayas/54-In_Guezzam.jpg",
    tags: {
    desert: 3,
    fast: 1,
    chill: 2,
    traditional: 3,
    family: 2,
    low_budget: 3,
    historic: 2,
    local: 3
    },
  },
  touggourt: {
    name: "Touggourt",
    demonym: "TOUGGOURTIENNE",
    emoji: "🌴🏙️",
    tagline: "Huge oasis energy, low key vibes.",
    description: "You are the bustling heartbeat of the palm groves. You have a little bit of everything and always make everyone feel right at home.",
    vibe_tag: "Palm groves and desert hospitality",
    image: "assets/wilayas/55-Touggourt.jpg",
    tags: {
    desert: 3,
    fast: 2,
    chill: 1,
    urban: 2,
    traditional: 2,
    nightlife: 1,
    family: 3,
    low_budget: 2,
    mid_budget: 1,
    historic: 1,
    modern: 2,
    local: 2,
    touristy: 1
    },
  },
  djanet: {
    name: "Djanet",
    demonym: "DJANETIENNE",
    emoji: "🎨✨",
    tagline: "UNESCO vibes and bucket-list views.",
    description: "You are breathtaking and iconic. People travel from all over just to catch a glimpse of your legendary natural beauty.",
    vibe_tag: "Tassili dreams and lunar landscapes",
    image: "assets/wilayas/56-Djanet.jpg",
    tags: {
    desert: 3,
    chill: 3,
    traditional: 2,
    family: 1,
    low_budget: 1,
    mid_budget: 2,
    historic: 3,
    local: 1,
    touristy: 3
    },
  },
  el_meghaier: {
    name: "El Meghaier",
    demonym: "EL MEGHAIERIENNE",
    emoji: "🌙🌾",
    tagline: "Cool, calm, and collected in the dunes.",
    description: "You are the definition of 'low-key.' You don't need a crowd to be happy—just good dates and quiet desert nights.",
    vibe_tag: "Oasis life in the golden dunes",
    image: "assets/wilayas/57-El_Meghaier.jpg",
    tags: {
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
  el_meniaa: {
    name: "El Meniaa",
    demonym: "EL MENIAÏENNE",
    emoji: "📍⚖️",
    tagline: "The perfect crossroads for your next chapter.",
    description: "You are the ultimate connector. You bridge the north and south, balancing tradition with a forward-looking mindset.",
    vibe_tag: "Ancient paths in the desert heart",
    image: "assets/wilayas/58-El_Meniaa.jpg",
    tags: {
    desert: 3,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    family: 2,
    low_budget: 2,
    mid_budget: 1,
    historic: 2,
    modern: 1,
    local: 2,
    touristy: 1
    },
  },
  aflou: {
    name: "Aflou",
    demonym: "AFLOUIENNE",
    emoji: "🏔️❄️",
    tagline: "Mountain air and cozy sweater vibes.",
    description: "You are the refreshing escape from the heat. You love high altitudes, snowy winters, and a cozy, traditional mountain lifestyle.",
    vibe_tag: "Highland winds and steppe adventures",
    image: "assets/wilayas/59-Aflou.jpg",
    tags: {
    mountain: 3,
    temperate: 2,
    chill: 3,
    urban: 1,
    traditional: 3,
    family: 3,
    low_budget: 3,
    historic: 2,
    local: 3
    },
  },
  barika: {
    name: "Barika",
    demonym: "BARIKIENNE",
    emoji: "🌾🏠",
    tagline: "Keeping it steady on the plains.",
    description: "You are reliable and down-to-earth. You represent the hardworking spirit of the plains, where life is steady and community comes first.",
    vibe_tag: "Heart of the plains, vibrant spirit",
    image: "assets/wilayas/60-Barika.jpg",
    tags: {
    temperate: 3,
    chill: 3,
    urban: 1,
    traditional: 2,
    family: 3,
    low_budget: 3,
    historic: 1,
    modern: 1,
    local: 3
    },
  },
  ksar_chellala: {
    name: "Ksar Chellala",
    demonym: "KSAR CHELLALIENNE",
    emoji: "🧶✨",
    tagline: "The quiet soul of the high plains.",
    description: "You are the definition of low-key and authentic. You love keeping things traditional and appreciate the slow, steady rhythm of life away from the big city noise.",
    vibe_tag: "Desert gateway and historical charm",
    image: null,
    tags: {
    temperate: 2,
    chill: 3,
    traditional: 3,
    family: 2,
    low_budget: 3,
    historic: 2,
    local: 3
    },
  },
  messaad: {
    name: "Messaad",
    demonym: "MESSAADIENNE",
    emoji: "🏜️🐪",
    tagline: "Your gateway to the vast desert horizon.",
    description: "You are grounded, resilient, and deeply connected to your roots. You’ve got a rugged spirit and prefer the wide-open spaces of the Saharan edge over anything else.",
    vibe_tag: "Steppe soul and rugged beauty",
    image: "assets/wilayas/62-Messaad.jpg",
    tags: {
    desert: 3,
    chill: 2,
    urban: 1,
    traditional: 2,
    family: 3,
    low_budget: 2,
    mid_budget: 1,
    historic: 1,
    modern: 1,
    local: 2
    },
  },
  a_n_oussara: {
    name: "Aïn Oussara",
    demonym: "AÏN OUSSARIENNE",
    emoji: "🏗️📈",
    tagline: "The rising star of the plains.",
    description: "You are focused, ambitious, and always on the move. You’re building your future and don’t have time for anything that doesn't help you level up.",
    vibe_tag: "Highland energy and vast horizon",
    image: "assets/wilayas/63-A_n_Oussara.jpg",
    tags: {
    temperate: 2,
    fast: 3,
    urban: 2,
    traditional: 1,
    nightlife: 1,
    family: 1,
    low_budget: 2,
    mid_budget: 1,
    modern: 3,
    local: 2
    },
  },
  boussa_da: {
    name: "Boussaâda",
    demonym: "BOUSSAÂDIENNE",
    emoji: "🎨✨",
    tagline: "Where art and desert magic collide.",
    description: "You’re an absolute creative soul with a poetic vibe. You love beautiful things, hidden gems, and the kind of aesthetic that looks perfect on your feed.",
    vibe_tag: "Gateway to the Sahara's golden gate",
    image: "assets/wilayas/64-Boussa_da.jpg",
    tags: {
    mountain: 1,
    desert: 2,
    temperate: 1,
    fast: 1,
    chill: 2,
    urban: 1,
    traditional: 2,
    nightlife: 1,
    family: 1,
    low_budget: 1,
    mid_budget: 2,
    historic: 2,
    modern: 1,
    local: 1,
    touristy: 3
    },
  },
  el_abiodh_sidi_cheikh: {
    name: "El Abiodh Sidi Cheikh",
    demonym: "EL ABIODHIENNE",
    emoji: "🕌💫",
    tagline: "Keep it sacred, keep it real.",
    description: "You have a deep respect for history and traditions that have lasted for centuries. You aren't into trends—you care about what actually matters.",
    vibe_tag: "Desert winds and nomadic memories",
    image: "assets/wilayas/65-El_Abiodh_Sidi_Cheikh.jpg",
    tags: {
    mountain: 1,
    desert: 3,
    chill: 3,
    traditional: 3,
    family: 2,
    low_budget: 3,
    historic: 3,
    local: 3
    },
  },
  el_kantara: {
    name: "El Kantara",
    demonym: "EL KANTARIENNE",
    emoji: "🏛️📸",
    tagline: "The ultimate aesthetic transition point.",
    description: "You are the bridge between two worlds, and everyone notices your unique style. You live for epic views and documenting the beauty around you.",
    vibe_tag: "Gateway to the canyon's grand beauty",
    image: "assets/wilayas/66-El_Kantara.jpg",
    tags: {
    mountain: 2,
    desert: 1,
    temperate: 1,
    chill: 2,
    traditional: 2,
    family: 2,
    low_budget: 1,
    mid_budget: 2,
    historic: 3,
    local: 1,
    touristy: 3
    },
  },
  bir_el_ater: {
    name: "Bir El Ater",
    demonym: "BIR EL ATERIENNE",
    emoji: "⛰️⚒️",
    tagline: "Tough, rugged, and mountain-made.",
    description: "You’re built for the grind and thrive in environments that require grit. You’re definitely not a softie, and you love being in the heart of the action.",
    vibe_tag: "Frontier spirit in the desert sun",
    image: null,
    tags: {
    mountain: 3,
    temperate: 1,
    fast: 2,
    urban: 1,
    traditional: 1,
    nightlife: 1,
    family: 1,
    low_budget: 2,
    mid_budget: 1,
    modern: 2,
    local: 3
    },
  },
  ksar_el_boukhari: {
    name: "Ksar El Boukhari",
    demonym: "KSAR EL BOUKHARIENNE",
    emoji: "🏔️🏘️",
    tagline: "Old school vibes in the mountains.",
    description: "You have an 'old soul' energy that people find super comforting. You love classic aesthetics, mountain air, and keeping your inner circle close.",
    vibe_tag: "Ancient trade routes and mountain air",
    image: "assets/wilayas/68-Ksar_El_Boukhari.jpg",
    tags: {
    mountain: 3,
    temperate: 2,
    chill: 2,
    urban: 1,
    traditional: 3,
    family: 3,
    low_budget: 2,
    historic: 3,
    local: 2,
    touristy: 1
    },
  },
  el_aricha: {
    name: "El Aricha",
    demonym: "EL ARICHIENNE",
    emoji: "🐑🌌",
    tagline: "Total main character, off the grid.",
    description: "You don't need anyone's validation to know you're cool. You prefer peace, quiet, and staying completely away from the drama of the fast lane.",
    vibe_tag: "High plateau charm and open roads",
    image: "assets/wilayas/69-El_Aricha.jpg",
    tags: {
    desert: 1,
    temperate: 2,
    chill: 3,
    traditional: 2,
    family: 2,
    low_budget: 3,
    historic: 1,
    local: 3
    },
  },
};
